# profile for easier view development with spring dev tools outside of docker
# TODO implement prometheus push model to enable ip switching
spring.config.activate.on-profile: view

management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
spring:
  application:
    name: app-view
  devtools:
    restart:
      enabled: true
  h2:
    console:
      enabled: false
  graphql:
    graphiql:
      enabled: false
  mvc:
    log-request-details: true

logging:
  level:
    org:
      springframework:
        web: debug