services:
  backend:
    image: project-base/app:latest
    networks:
      - my-network
    ports:
      - 8080:8080
#  caddy:
#    image: caddy:2.8.4-alpine
#    restart: unless-stopped
#    ports:
#      - "80:80"
#      - "443:443"
#      - "443:443/udp"
#    volumes:
#      - ./Caddyfile:/etc/caddy/Caddyfile
#      - caddy_data:/data
#      - caddy_config:/config
#    networks:
#      - my-network
  ngrok:
    image: ngrok/ngrok:2-alpine
    restart: unless-stopped
    command:
      - "start"
      - "--all"
      - "--config"
      - "/etc/ngrok.yml"
    volumes:
      - ./ngrok.yml:/etc/ngrok.yml
    ports:
      - 4040:4040
    networks:
      - my-network

#volumes:
#  caddy_data:
#  caddy_config:

networks:
  my-network:
    driver: bridge